### ISSUE TITLE
intelhex compat.py broken in Python 3.9

### ISSUE THREAD

**Issue by ih8ms** [laneboysrc/LPC81x-ISP-tool#1]
Running Ubuntu 21.04 with Python 3.9.5:

```
./lpc81x_isp.py
Traceback (most recent call last):
  File "/home/sbreit/git/LPC81x-ISP-tool/./lpc81x_isp.py", line 63, in <module>
    from intelhex import IntelHex, HexRecordError
  File "/home/sbreit/git/LPC81x-ISP-tool/intelhex/__init__.py", line 44, in <module>
    from intelhex.compat import (
  File "/home/sbreit/git/LPC81x-ISP-tool/intelhex/compat.py", line 60, in <module>
    array_tobytes = getattr(array.array, "tobytes", array.array.tostring)
AttributeError: type object 'array.array' has no attribute 'tostring'
```

'tostring' is deprecated and was removed in Python 3.9.5. There also is an issue in the python-tostring project: https://github.com/python-intelhex/intelhex/issues/45

For me, renaming the intelhex folder and using python3-intelhex from the apt repo fixed the issue.

**Comment by laneboysrc** [comment]
Thanks for reporting, I removed the outdated intelhex copy and added instructions how to install the required modules.

cheers, Werner
